apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
        - name: quiz-backend
          image: backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
spec:
  selector:
    app: quiz-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
