apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
    
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: aws-0-ap-south-1.pooler.supabase.com:6543  
    isDefault: false
    database: postgres
    user: postgres.uuridtiptmnbgdejobmn
    secureJsonData:
      password: P@ndey0316
    jsonData:
      sslmode: disable  
      postgresVersion: 1200  
      timescaledb: false  
