apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: quiz-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quiz-backend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100
